version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: todolist_mongo
    ports:
      - "27017:27017" # Mappe le port 27017 du conteneur MongoDB au port 27017 de votre machine
    volumes:
      - mongo_data:/data/db # Stocke les données MongoDB sur votre machine pour persistance

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist_backend
    ports:
      - "3001:3001" # Mappe le port 3000 du conteneur NestJS au port 3000 de votre machine
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todolist # URI de connexion à MongoDB
    command: npm run start:debug # Use the development command

volumes:
  mongo_data:
    driver: local
